robot_test:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  chain_position_controller:
    type: position_controllers/JointPositionController
    joint: Joint2
